// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.dac.api;

import com.dremio.dac.annotations.OpenApiResource;
import com.dremio.dac.api.ErrorResponseConverter;
import com.dremio.test.api.GetBody;
import com.dremio.test.api.PostBody;
import com.dremio.test.api.PostChunk;
import com.dremio.test.api.ResponseContent;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;

@OpenApiResource(serverPathSpec = "api/v4/*")
public class RestResourceImpl implements RestResource {

  @Override
  public GetBody post(
    PostBody request,
    String filter) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests"));
  }

  @Override
  public GetBody get(
    String path,
    Integer otherPath) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests/{path}/{otherPath}"));
  }

  @Override
  public GetBody withInParam(
    String id,
    Integer offset) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests/with-in-param/{id}/{offset}"));
  }

  @Override
  public GetBody withInRepeatedParam(
    String id) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests/with-in-repeated-param/{id}"));
  }

  @Override
  public GetBody get1(
    String path) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests/{path}"));
  }

  @Override
  public ResponseContent list() {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests"));
  }

  @Override
  public ResponseContent put(
    PostBody request) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests"));
  }

  @Override
  public Response postPost-chunked(
    PostBody request) {
    throw new WebApplicationException(
        ErrorResponseConverter.notImplemented("/tests/post-chunked"));
  }
}
