// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

/**
 * Enum can be defined with const fields io oneOf.
*/
public enum EnumOneOf {
  /**
   * ABC1 description
  */
  ABC1,

  /**
   * DEF1 description
  */
  DEF1,
}
