// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

/**
 * Multi-line enum description to test
 * comments for enums.
*/
public enum Enum {
  /**
   * First enum value.
  */
  ABC,

  /**
   * Second enum value
  */
  CDE,
}
