// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import org.immutables.value.Value;

@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableError.class)
@JsonSerialize(as = ImmutableError.class)
public interface Error {
  String getType();

  /**
   * A human-readable explanation specific to this occurrence of the problem
  */
  @Nullable String getDetail();

  /**
   * A JSON pointer to locate the problem within the request's content
  */
  String getPointer();

  default ImmutableError.Builder toBuilder() {
    return ImmutableError.builder().from(this);
  }
}
