// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.Duration;
import java.time.ZonedDateTime;
import java.util.List;
import javax.annotation.Nullable;
import javax.validation.constraints.Email;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import org.immutables.value.Value;

/**
 * GET response body.
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableGetBody.class)
@JsonSerialize(as = ImmutableGetBody.class)
public interface GetBody {
  @Nullable Enum getEnumValue();

  /**
   * Int value.
  */
  @Min(value = 10)
  @Max(value = 20)
  @Nullable Integer getIntValue1();

  /**
   * Long value.
  */
  @Nullable Long getLongValue();

  /**
   * String value.
  */
  @Nullable String getStringValue1();

  /**
   * Email value.
  */
  @Email()
  @Nullable String getEmail();

  /**
   * Float value.
  */
  @Nullable Float getFloatValue();

  /**
   * Double value.
  */
  @Nullable Double getDoubleValue();

  /**
   * Timestamp value.
  */
  @Nullable ZonedDateTime getTimestampValue();

  /**
   * Duration value.
  */
  @Nullable Duration getDurationValue();

  /**
   * String list.
  */
  @Nullable List<String> getStringList();

  /**
   * Inline oneof.
  */
  @Nullable GetBodyInlineOneof getInlineOneof();

  /**
   * Oneof of consts works as a enum.
  */
  @Nullable GetBodyEnumOneof getEnumOneof();

  default ImmutableGetBody.Builder toBuilder() {
    return ImmutableGetBody.builder().from(this);
  }
}
