// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

/**
 * Oneof of consts works as a enum.
*/
public enum GetBodyEnumOneof {
  /**
   * Value1 description.
  */
  VALUE1,

  /**
   * Value2 description.
  */
  VALUE2,
}
