// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import org.immutables.value.Value;

/**
 * Int choice
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableIntChoice.class)
@JsonSerialize(as = ImmutableIntChoice.class)
public interface IntChoice {
  @Nullable Integer getIntValue();

  default ImmutableIntChoice.Builder toBuilder() {
    return ImmutableIntChoice.builder().from(this);
  }
}
