// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import org.immutables.value.Value;

/**
 * Test oneof message with field expansion for references
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableOneOf.class)
@JsonSerialize(as = ImmutableOneOf.class)
public abstract class OneOf {
  /**
   * String choice
  */
  public abstract @Nullable String getStringValue();

  /**
   * Int choice
  */
  public abstract @Nullable Integer getIntValue();

  /**
   * Int choice wrapper, won't exist as a message
  */
  public abstract @Nullable Integer getAnotherIntValue();

  public ImmutableOneOf.Builder toBuilder() {
    return ImmutableOneOf.builder().from(this);
  }

  @Value.Check
  protected void validate() {
    int setFields = 0;
    if (getStringValue() != null) {
      setFields++;
    }
    if (getIntValue() != null) {
      setFields++;
    }
    if (getAnotherIntValue() != null) {
      setFields++;
    }
    if (setFields > 1) {
      throw new RuntimeException("More than one field is set in a oneof.");
    }
  }
}
