// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import org.immutables.value.Value;

/**
 * Chunk of the post response.
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutablePostChunk.class)
@JsonSerialize(as = ImmutablePostChunk.class)
public interface PostChunk {
  @Nullable String getText();

  default ImmutablePostChunk.Builder toBuilder() {
    return ImmutablePostChunk.builder().from(this);
  }
}
