// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import org.immutables.value.Value;

/**
 * An RFC 9457 problem object
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableProblem.class)
@JsonSerialize(as = ImmutableProblem.class)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ValidationProblem.class, name = "ABC1"),
  @JsonSubTypes.Type(value = RuntimeProblem.class, name = "DEF1"),
})
public interface Problem {
  /**
   * A URI reference that identifies the problem type
  */
  @Nullable String getType();

  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem
  */
  @Min(value = 100)
  @Max(value = 599)
  @Nullable Long getStatus();

  /**
   * A human-readable summary of the problem type
  */
  @Nullable String getTitle();

  /**
   * A human-readable explanation specific to this occurrence of the problem
  */
  @Nullable String getDetail();

  @Nullable
  ImmutableProblem.Builder toBuilder();
}
