// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import org.immutables.value.Value;

/**
 * Response content
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableResponseContent.class)
@JsonSerialize(as = ImmutableResponseContent.class)
public interface ResponseContent {
  @Nullable String getName();

  default ImmutableResponseContent.Builder toBuilder() {
    return ImmutableResponseContent.builder().from(this);
  }
}
