// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.dremio.test.api.ImmutableProblem.Builder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.immutables.value.Value;

@Value.Immutable
@JsonDeserialize(as = ImmutableRuntimeProblem.class)
@JsonSerialize(as = ImmutableRuntimeProblem.class)
public interface RuntimeProblem extends Problem {
  /**
   * Runtime problem cause
  */
  String getCause();

  @Override
  Builder toBuilder();
}
