// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.annotation.Nullable;
import javax.validation.constraints.Pattern;
import org.immutables.value.Value;

/**
 * String choice
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableStringChoice.class)
@JsonSerialize(as = ImmutableStringChoice.class)
public interface StringChoice {
  @Pattern(regexp = "[0-9]+")
  @Nullable String getStringValue();

  default ImmutableStringChoice.Builder toBuilder() {
    return ImmutableStringChoice.builder().from(this);
  }
}
