// DO NOT EDIT: generated by Dremio openapi-generator.
package com.dremio.test.api2;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;
import javax.annotation.Nullable;
import org.immutables.value.Value;

/**
 * Includes a message from the other file.
*/
@Value.Immutable
@Value.Style(builderVisibility = Value.Style.BuilderVisibility.PUBLIC)
@JsonDeserialize(as = ImmutableBody2.class)
@JsonSerialize(as = ImmutableBody2.class)
public interface Body2 {
  @Nullable com.dremio.test.api.GetBody getValue();

  com.dremio.test.api.GetBody getRequiredValue();

  /**
   * Referenced enum.
  */
  @Nullable List<com.dremio.test.api.Enum> getEnumList();

  @Nullable List<com.dremio.test.api.Enum> getEnumArray();

  default ImmutableBody2.Builder toBuilder() {
    return ImmutableBody2.builder().from(this);
  }
}
