// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jOVQPOOOOQO'#C`'#C`O_QPO'#C_OOQO'#Cb'#CbOmQPO'#C^OOQO'#Cc'#CcOOQO'#Cd'#CdQVQPOOOVQPO,58xOOQO-E6b-E6bOOQO'#Ca'#CaOOQO1G.d1G.d",
  stateData: "u~OZOS~O[PO^RO~OXVX[VX]RX^VX~O]WO~OZ[~",
  goto: "yXPPY^bilYsTUOVTSOVSQOVRYWRZWSTOVRYWQVORXV",
  nodeNames: "⚠ DremioSemanticSearch Filter FilterKeyword Word FilterValue QuotedString SearchText",
  maxTerm: 14,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*O~RqX^#Ypq#Yqr#}rs%Xst#}tu#}uw#}z!Q#}!Q![#}![!]'q!]!^#}!a!c#}!c!}#}#Q#R#}#R#S#}#T#o#}#y#z#Y$f$g#Y$g#BY#}#BY#BZ'v#BZ$IS#}$IS$I_'v$I_$I|#}$I|$JO'v$JO$JT#}$JT$JU'v$JU$KV#}$KV$KW'v$KW&FU#}&FU&FV'v&FV;'S#};'S;=`%R<%lO#}~#_YZ~X^#Ypq#Y#y#z#Y$f$g#Y#BY#BZ#Y$IS$I_#Y$I|$JO#Y$JT$JU#Y$KV$KW#Y&FU&FV#Y~$S_[~qr#}st#}tu#}uw#}z!Q#}!Q![#}!]!^#}!a!c#}!c!}#}#Q#R#}#R#S#}#T#o#}$g;'S#};'S;=`%R<%lO#}~%UP;=`<%l#}~%[Wpq%Xqr%Xrs%ts#O%X#O#P%y#P;'S%X;'S;=`'k<%lO%X~%yO^~~%|Xrs%X!P!Q%X#O#P%X#U#V%X#Y#Z%X#b#c%X#f#g%X#h#i%X#i#j&i~&lR!Q![&u!c!i&u#T#Z&u~&xR!Q!['R!c!i'R#T#Z'R~'UR!Q!['_!c!i'_#T#Z'_~'bR!Q![%X!c!i%X#T#Z%X~'nP;=`<%l%X~'vO]~~'}oZ~[~X^#Ypq#Yqr#}st#}tu#}uw#}z!Q#}!Q![#}!]!^#}!a!c#}!c!}#}#Q#R#}#R#S#}#T#o#}#y#z#Y$f$g#Y$g#BY#}#BY#BZ'v#BZ$IS#}$IS$I_'v$I_$I|#}$I|$JO'v$JO$JT#}$JT$JU'v$JU$KV#}$KV$KW'v$KW&FU#}&FU&FV'v&FV;'S#};'S;=`%R<%lO#}",
  tokenizers: [0],
  topRules: {"DremioSemanticSearch":[0,1]},
  tokenPrec: 34
})
