// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  DremioSemanticSearch = 1,
  Filter = 2,
  FilterKeyword = 3,
  Word = 4,
  FilterValue = 5,
  QuotedString = 6,
  SearchText = 7
