/*
 * Copyright (C) 2017-2019 Dremio Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.tools.openapigenerator;

import java.io.BufferedWriter;
import java.io.IOException;
import java.util.List;

public final class Header {
  private static final List<String> HEADER_LINES =
      List.of("// DO NOT EDIT: generated by Dremio openapi-generator.");

  private Header() {}

  /** Writes license lines. */
  public static void write(BufferedWriter writer) throws IOException {
    for (String line : HEADER_LINES) {
      writer.write(line);
      writer.newLine();
    }
  }
}
